backend:
  name: github
  repo: ajudafacity/ajudafacitysistemas
  branch: main
  auth_type: implicit
  app_id: Ov23liVx7DEbai6Og3mE

media_folder: static/img
public_folder: /img

collections:
  - name: "docs"
    label: "Documentação"
    folder: "docs"  # Pasta do Docusaurus onde ficam os arquivos de documentação
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumo", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
