backend:
  name: git-gateway
  branch: main  # O branch onde o CMS irá fazer as modificações

media_folder: "static/img/uploads"  # Onde os arquivos enviados serão salvos
public_folder: "/img/uploads"

collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
